In [2]:
import numpy as np

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1 : 5])

[2 3 4 5]


In [6]:
print(arr[4 : ])

[5 6 7]


In [8]:
print(arr[ : 5])

[1 2 3 4 5]


Negative Slicing

In [11]:
print(arr[-3 : -1])

[5 6]


Step

In [14]:
print(arr[1 : 5 : 2])

[2 4]


In [17]:
print(arr[::2])

[1 3 5 7]


Slicing 2-D Arrays

In [43]:
import numpy as np

In [45]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr1[1, 1 : 4])

[7 8 9]


In [47]:
print(arr1[0 : 2, 2])

[3 8]


In [49]:
print(arr1[0 : 2, 1 :4])

[[2 3 4]
 [7 8 9]]
