In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6,])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
arr1 = np.array((1, 2, 3,))
print(arr1)

[1 2 3]


0-D Array

In [7]:
arr2 = np.array((42))
print(arr2)

42


1-D Array


In [8]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3)

[1 2 3 4 5]


2-D Array


In [11]:
arr4 = np.array([[1, 2, 3,], [4, 5, 6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


3-D Array

In [12]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


How to check the number of Dimensions in an array?

In [17]:
a = np.array(1)
b = np.array([1, 2])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


Higher Dimensional Arrays

Create an array with 5 dmiensions and verify it has 5 dimensions

In [4]:
import numpy as np
arr6 = np.array([1, 2, 3, 4], ndmin = 5)
print(arr6)
print('Number of Dimensions : ', arr6.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimensions :  5
